
on:
  workflow_run:
    types:
      - requested
    workflows:
      - Test workflow (labeled)

jobs:
  echo:
    name: write context info
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo "${{ github }}"
          echo "${{ job }}"
