# Test workflow
name: Test workflow (labeled)

on:
  workflow_dispatch:
    inputs:
      example:
        name: example
        description: test thing
        type: string
  pull_request:
    types: [labeled, unlabeled]
  issue_comment:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo github object
        shell: bash
        run: |
          cat <<EOF
          ${{ toJSON(github) }}
          EOF
      - name: echo inputs
        shell: bash
        run: |
          cat <<EOF
          ${{ toJSON(inputs) }}
          EOF
      - name: labeled
        shell: bash
        run: echo "labeled"
      - name: get collaborator status
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          for user in sRassmann dkuegler m-reuter;
          do
            if gh api \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/${{ github.repository }}/collaborators/sRassmann
            then
              echo "user $user: true"
             else
              echo "user $user: false"
            fi
          done
