# Test workflow
name: Test workflow (labeled)

on:
  workflow_dispatch:
    inputs:
      example:
        name: example
        description: test thing
        type: string
  pull_request:
    types: [labeled, unlabeled]
  issue_comment:
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo github object
        shell: bash
        run: |
          cat <<EOF
          ${{ toJSON(github) }}
          EOF
      - name: echo inputs
        shell: bash
        run: |
          cat <<EOF
          ${{ toJSON(inputs) }}
          EOF
      - name: labeled
        shell: bash
        run: echo "labeled"
      - name: get collaborator status
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/dkuegler/workflow-test/collaborators/sRassmann
          echo "dkuegler:"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Deep-MI/FastSurfer/collaborators/dkuegler
          echo "m-reuter:"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Deep-MI/FastSurfer/collaborators/m-reuter
          echo "emadRad:"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/Deep-MI/FastSurfer/collaborators/emadRad
          echo "missing:"
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/dkuegler/workflow-test/collaborators/oidjgusghishltiu
