# Test workflow
name: Test workflow (labeled)

on:
  workflow_dispatch:
    inputs:
      example:
        name: example
        description: test thing
        type: string
  pull_request:
    types: [labeled, unlabeled]
  issue_comment:
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo github object
        shell: bash
        run: |
          cat <<EOF
          ${{ toJSON(github) }}
          EOF
      - name: echo inputs
        shell: bash
        run: |
          cat <<EOF
          ${{ toJSON(inputs) }}
          EOF
      - name: labeled
        shell: bash
        run: echo "labeled"
